spring:
  cloud:
    nacos:
      discovery:
        ip: 192.168.31.60
        server-addr: ${spring.cloud.nacos.discovery.ip}:8848
    stream:
      rocketmq:
        binder:
          name-server: 172.17.0.1:9876
#  datasource:
#    dynamic:
#      primary: master
#      datasource:
#        master:
#          url: jdbc:mysql://172.17.0.1:3306/bonelf-gateway?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
#          username: bonelf
#          password: 567215
#          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 172.17.0.1
    port: 6379
    password: '567215'